# generated by appcreator
from django.contrib import admin
from reversion.admin import VersionAdmin
from . models import (
    Autor,
    KeyWord,
    Ort,
    Stelle,
    Text,
    SpatialCoverage,
    UseCase,
    Event
)


@admin.register(Autor)
class AutorAdmin(VersionAdmin):
    pass


@admin.register(KeyWord)
class KeyWordAdmin(VersionAdmin):
    pass

@admin.register(Ort)
class OrtAdmin(VersionAdmin):
    pass


@admin.register(Stelle)
class StelleAdmin(VersionAdmin):
    pass


@admin.register(Text)
class TextAdmin(VersionAdmin):
    pass


@admin.register(UseCase)
class UseCaseAdmin(VersionAdmin):
    pass


@admin.register(SpatialCoverage)
class SpatialCoverageAdmin(VersionAdmin):
    pass

@admin.register(Event)
class SpatialCoverageAdmin(VersionAdmin):
    pass
