# generated by appcreator
from django.contrib import admin
from . models import (
    Autor,
    KeyWord,
    Ort,
    Stelle,
    Text,
    SpatialCoverage,
    UseCase,
)
admin.site.register(Autor)
admin.site.register(KeyWord)
admin.site.register(Ort)
admin.site.register(Stelle)
admin.site.register(Text)
admin.site.register(UseCase)
admin.site.register(SpatialCoverage)
