# generated by appcreator
from django.conf.urls import url
from . import dal_views

app_name = 'archiv'
urlpatterns = [
    url(
        r'^autor-autocomplete/$',
        dal_views.AutorAC.as_view(),
        name='autor-autocomplete'
    ),
    url(
        r'^ort-autocomplete/$',
        dal_views.OrtAC.as_view(),
        name='ort-autocomplete'
    ),
]
