# generated by appcreator
from django.conf.urls import url
from . import dal_views

app_name = 'archiv'
urlpatterns = [
    url(
        r'^autor-autocomplete/$',
        dal_views.AutorAC.as_view(),
        name='autor-autocomplete'
    ),
    url(
        r'^keyword-autocomplete/$',
        dal_views.KeyWordAC.as_view(),
        name='keyword-autocomplete'
    ),
    url(
        r'^schlagwort-autocomplete/$',
        dal_views.Schlagwort.as_view(),
        name='schlagwort-autocomplete'
    ),
    url(
        r'^eigenname-autocomplete/$',
        dal_views.Eigenname.as_view(),
        name='eigenname-autocomplete'
    ),
    url(
        r'^ort-autocomplete/$',
        dal_views.OrtAC.as_view(),
        name='ort-autocomplete'
    ),
    url(
        r'^stelle-autocomplete/$',
        dal_views.StelleAC.as_view(),
        name='stelle-autocomplete'
    ),
    url(
        r'^text-autocomplete/$',
        dal_views.TextAC.as_view(),
        name='text-autocomplete'
    ),
    url(
        r'^usecase-autocomplete/$',
        dal_views.UseCaseAC.as_view(),
        name='usecase-autocomplete'
    ),
]
