from django.urls import path

from . import views
from archiv.endpoint_views import (
    KeyWordEndpoint, NlpDataStelle, key_word_by_century, KeyWordStelle, StopWordListView, KeyWordAuthorEndpoint
)

from . import tei_views
from . import copy_views

app_name = 'archiv'
urlpatterns = [
    path(
        'spatialcoverage-copy/',
        copy_views.copy_beleg,
        name='copy_beleg'
    ),
    path(
        'stelle-copy/',
        copy_views.copy_stelle,
        name='copy_stelle'
    ),
    path(
        'usecase/',
        views.UseCaseListView.as_view(),
        name='usecase_browse'
    ),
    path(
        'usecase/detail/<int:pk>',
        views.UseCaseDetailView.as_view(),
        name='usecase_detail'
    ),
    path(
        'usecase/create/',
        views.UseCaseCreate.as_view(),
        name='usecase_create'
    ),
    path(
        'usecase/edit/<int:pk>',
        views.UseCaseUpdate.as_view(),
        name='usecase_edit'
    ),
    path(
        'usecase/delete/<int:pk>',
        views.UseCaseDelete.as_view(),
        name='usecase_delete'),
    path(
        'usecase-timetable-data/<int:pk>',
        views.get_usecase_timetable_json,
        name='usecase_timetable_json'),
    path(
        'spatialcoverage/',
        views.SpatialCoverageListView.as_view(),
        name='spatialcoverage_browse'
    ),
    path(
        'spatialcoverage/detail/<int:pk>',
        views.SpatialCoverageDetailView.as_view(),
        name='spatialcoverage_detail'
    ),
    path(
        'spatialcoverage/create/',
        views.SpatialCoverageCreate.as_view(),
        name='spatialcoverage_create'
    ),
    path(
        'spatialcoverage/edit/<int:pk>',
        views.SpatialCoverageUpdate.as_view(),
        name='spatialcoverage_edit'
    ),
    path(
        'spatialcoverage/delete/<int:pk>',
        views.SpatialCoverageDelete.as_view(),
        name='spatialcoverage_delete'),
    path(
        'autor/',
        views.AutorListView.as_view(),
        name='autor_browse'
    ),
    path(
        'autor/detail/<int:pk>',
        views.AutorDetailView.as_view(),
        name='autor_detail'
    ),
    path(
        'autor/create/',
        views.AutorCreate.as_view(),
        name='autor_create'
    ),
    path(
        'autor/edit/<int:pk>',
        views.AutorUpdate.as_view(),
        name='autor_edit'
    ),
    path(
        'autor/delete/<int:pk>',
        views.AutorDelete.as_view(),
        name='autor_delete'),
    path(
        'keyword/',
        views.KeyWordListView.as_view(),
        name='keyword_browse'
    ),
    path(
        'keyword/century/<int:pk>',
        key_word_by_century,
        name='keyword_by_century'
    ),
    path(
        'keyword-network/',
        KeyWordEndpoint.as_view(),
        name='keyword_data'
    ),
    path(
        'keyword-author-network/',
        KeyWordAuthorEndpoint.as_view(),
        name='keyword_data'
    ),
    path(
        'keyword/detail/<int:pk>',
        views.KeyWordDetailView.as_view(),
        name='keyword_detail'
    ),
    path(
        'keyword/create/',
        views.KeyWordCreate.as_view(),
        name='keyword_create'
    ),
    path(
        'keyword/edit/<int:pk>',
        views.KeyWordUpdate.as_view(),
        name='keyword_edit'
    ),
    path(
        'keyword/delete/<int:pk>',
        views.KeyWordDelete.as_view(),
        name='keyword_delete'),
    path(
        'ort/',
        views.OrtListView.as_view(),
        name='ort_browse'
    ),
    path(
        'ort/detail/<int:pk>',
        views.OrtDetailView.as_view(),
        name='ort_detail'
    ),
    path(
        'ort/create/',
        views.OrtCreate.as_view(),
        name='ort_create'
    ),
    path(
        'ort/edit/<int:pk>',
        views.OrtUpdate.as_view(),
        name='ort_edit'
    ),
    path(
        'ort/delete/<int:pk>',
        views.OrtDelete.as_view(),
        name='ort_delete'),
    path(
        'stelle/',
        views.StelleListView.as_view(),
        name='stelle_browse'
    ),
    path(
        'stelle/detail/<int:pk>',
        views.StelleDetailView.as_view(),
        name='stelle_detail'
    ),
    path(
        'stelle/create/',
        views.StelleCreate.as_view(),
        name='stelle_create'
    ),
    path(
        'stelle/edit/<int:pk>',
        views.StelleUpdate.as_view(),
        name='stelle_edit'
    ),
    path(
        'stelle/delete/<int:pk>',
        views.StelleDelete.as_view(),
        name='stelle_delete'),
    path(
        'text/',
        views.TextListView.as_view(),
        name='text_browse'
    ),
    path(
        'text/detail/<int:pk>',
        views.TextDetailView.as_view(),
        name='text_detail'
    ),
    path(
        'text/create/',
        views.TextCreate.as_view(),
        name='text_create'
    ),
    path(
        'text/edit/<int:pk>',
        views.TextUpdate.as_view(),
        name='text_edit'
    ),
    path(
        'text/delete/<int:pk>',
        views.TextDelete.as_view(),
        name='text_delete'),
    path(
        'text/xml-tei/<int:pk>',
        tei_views.text_to_tei,
        name='text_xml'
    ),
    path(
        'event/',
        views.EventListView.as_view(),
        name='event_browse'
    ),
    path(
        'event/detail/<int:pk>',
        views.EventDetailView.as_view(),
        name='event_detail'
    ),
    path(
        'event/create/',
        views.EventCreate.as_view(),
        name='event_create'
    ),
    path(
        'event/edit/<int:pk>',
        views.EventUpdate.as_view(),
        name='event_edit'
    ),
    path(
        'event/delete/<int:pk>',
        views.EventDelete.as_view(),
        name='event_delete'
    ),
    path(
        'nlp-data/',
        NlpDataStelle.as_view(),
        name='nlp_data'
    ),
    path(
        'kw-stelle/',
        KeyWordStelle.as_view(),
        name='keyword_stelle'
    ),
    path(
        'stopwords/',
        StopWordListView.as_view(),
        name='stopwords'
    ),
]
