# generated by appcreator
from django.conf.urls import url
from . import views

app_name = 'archiv'
urlpatterns = [
    url(
        r'^autor/$',
        views.AutorListView.as_view(),
        name='autor_browse'
    ),
    url(
        r'^autor/detail/(?P<pk>[0-9]+)$',
        views.AutorDetailView.as_view(),
        name='autor_detail'
    ),
    url(
        r'^autor/create/$',
        views.AutorCreate.as_view(),
        name='autor_create'
    ),
    url(
        r'^autor/edit/(?P<pk>[0-9]+)$',
        views.AutorUpdate.as_view(),
        name='autor_edit'
    ),
    url(
        r'^autor/delete/(?P<pk>[0-9]+)$',
        views.AutorDelete.as_view(),
        name='autor_delete'),
    url(
        r'^ort/$',
        views.OrtListView.as_view(),
        name='ort_browse'
    ),
    url(
        r'^ort/detail/(?P<pk>[0-9]+)$',
        views.OrtDetailView.as_view(),
        name='ort_detail'
    ),
    url(
        r'^ort/create/$',
        views.OrtCreate.as_view(),
        name='ort_create'
    ),
    url(
        r'^ort/edit/(?P<pk>[0-9]+)$',
        views.OrtUpdate.as_view(),
        name='ort_edit'
    ),
    url(
        r'^ort/delete/(?P<pk>[0-9]+)$',
        views.OrtDelete.as_view(),
        name='ort_delete'),
]
