# Generated by Django 3.2 on 2021-10-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_modelingprocess_modeling_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='word',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
