# Generated by Django 3.2 on 2021-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
