# Generated by Django 3.2 on 2021-11-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0025_remove_text_lang'),
        ('topics', '0004_topic_topic_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTopicRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_topics', to='archiv.stelle')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_related_texts', to='topics.topic')),
            ],
        ),
    ]
