# Generated by Django 3.2.9 on 2021-12-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_texttopicrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, help_text='Word/Token to be excluded from any processing', max_length=250, null=True, verbose_name='stop word')),
            ],
        ),
    ]
