# Generated by Django 3.1.5 on 2021-01-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='lat',
            field=models.FloatField(blank=True, help_text='Breitengrad', null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='ort',
            name='long',
            field=models.FloatField(blank=True, help_text='Längengrad', null=True, verbose_name='Längengrad'),
        ),
    ]
