# Generated by Django 3.1.5 on 2021-01-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='end_date',
            field=models.CharField(blank=True, help_text='bis', max_length=250, verbose_name='bis'),
        ),
        migrations.AddField(
            model_name='autor',
            name='name_lat',
            field=models.CharField(blank=True, help_text='Name (lat)', max_length=250, verbose_name='Name (lat)'),
        ),
        migrations.AddField(
            model_name='autor',
            name='start_date',
            field=models.CharField(blank=True, help_text='von', max_length=250, verbose_name='von'),
        ),
    ]
