# Generated by Django 3.1.5 on 2021-01-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('archiv', '0002_auto_20210112_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('zitat', models.CharField(blank=True, help_text='Zitat', max_length=250, verbose_name='Zitat')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
            ],
            options={
                'verbose_name': 'Edition',
                'ordering': ['zitat'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('title', models.CharField(blank=True, help_text='Titel', max_length=250, verbose_name='Titel')),
                ('jahrhundert', models.CharField(blank=True, help_text='Jahrhundert', max_length=250, verbose_name='Jahrundert')),
                ('start_date', models.CharField(blank=True, help_text='von', max_length=250, verbose_name='von')),
                ('end_date', models.CharField(blank=True, help_text='bis', max_length=250, verbose_name='bis')),
                ('kommentar', models.TextField(blank=True, help_text='Kommentar', null=True, verbose_name='Kommentar')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
                ('art', models.ForeignKey(blank=True, help_text='Textart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_text_art_skosconcept', to='vocabs.skosconcept', verbose_name='Textart')),
                ('autor', models.ManyToManyField(blank=True, help_text='Autor', related_name='rvn_text_autor_autor', to='archiv.Autor', verbose_name='Autor')),
                ('edition', models.ManyToManyField(blank=True, help_text='Edition', related_name='rvn_text_edition_edition', to='archiv.Edition', verbose_name='Edition')),
                ('ort', models.ManyToManyField(blank=True, help_text='Ort', related_name='rvn_text_ort_ort', to='archiv.Ort', verbose_name='Ort')),
            ],
            options={
                'verbose_name': 'Text',
                'ordering': ['title'],
            },
        ),
    ]
