# Generated by Django 3.1.5 on 2021-02-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_auto_20210218_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='stelle',
            name='zitat_stelle',
            field=models.CharField(blank=True, help_text='z.B. Seitenangaben', max_length=250, null=True, verbose_name='Zitat Stelle'),
        ),
    ]
