# Generated by Django 3.1.5 on 2021-02-23 12:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0003_stelle_zitat_stelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.TextField(blank=True, help_text='Kommentar', null=True, verbose_name='Kommentar')),
                ('exactish_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Lokalisierung einer Region', null=True, srid=4326, verbose_name='Relative sichere Ortsangabe')),
                ('fuzzy_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Ungefähre Lokalisierung einer Region', null=True, srid=4326, verbose_name='unsichere Ortsangabe')),
                ('key_word', models.ForeignKey(blank=True, help_text='Stichwort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_spatial_coverage', to='archiv.keyword', verbose_name='Stichwort')),
                ('stelle', models.ForeignKey(blank=True, help_text='Stelle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_spatial_coverage', to='archiv.stelle', verbose_name='Stelle')),
            ],
        ),
    ]
