# Generated by Django 3.1.5 on 2021-01-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('archiv', '0003_edition_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('zitat', models.TextField(blank=True, help_text='Zitat', null=True, verbose_name='Zitat')),
                ('translation', models.TextField(blank=True, help_text='Übersetzung', null=True, verbose_name='Übersetzung')),
                ('kommentar', models.TextField(blank=True, help_text='Kommentar', null=True, verbose_name='Kommentar')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
                ('key_word', models.ManyToManyField(blank=True, help_text='Stichwort', related_name='rvn_stelle_key_word_skosconcept', to='vocabs.SkosConcept', verbose_name='Stichwort')),
                ('text', models.ForeignKey(blank=True, help_text='Text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_stelle_text_text', to='archiv.text', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Stelle',
                'ordering': ['legacy_pk'],
            },
        ),
    ]
