# Generated by Django 3.1.5 on 2021-01-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0003_ort'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='ort',
            field=models.ForeignKey(blank=True, help_text='Ort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_autor_ort_ort', to='archiv.ort', verbose_name='Ort'),
        ),
    ]
