# Generated by Django 3.1.5 on 2021-01-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_stelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('stichwort', models.CharField(blank=True, help_text='Stichwort', max_length=250, verbose_name='Stichwort')),
                ('art', models.CharField(blank=True, help_text='Art des Stichworts', max_length=250, verbose_name='Art des Stichworts')),
                ('wurzel', models.CharField(blank=True, help_text='Wurzel', max_length=250, verbose_name='Wurzel')),
                ('kommentar', models.TextField(blank=True, help_text='Kommentar', null=True, verbose_name='Kommentar')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
            ],
            options={
                'verbose_name': 'Keyword',
                'ordering': ['stichwort'],
            },
        ),
        migrations.AlterField(
            model_name='stelle',
            name='key_word',
            field=models.ManyToManyField(blank=True, help_text='Stichwort', related_name='rvn_stelle_key_word_keyword', to='archiv.KeyWord', verbose_name='Stichwort'),
        ),
    ]
