# Generated by Django 3.1.5 on 2021-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_auto_20210223_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='stelle',
            name='display_label',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='automatic created label'),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='fuzzyness',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='1 sehr sicher, 10 sehr unsicher', verbose_name='Sicherheitsindikator'),
        ),
    ]
