# Generated by Django 3.1.5 on 2021-01-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_auto_20210113_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='stelle',
            name='summary',
            field=models.TextField(blank=True, help_text='Zusammenfassung', null=True, verbose_name='Zusammenfassung'),
        ),
    ]
