# Generated by Django 3.1.5 on 2021-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0009_auto_20210226_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='art',
            field=models.CharField(blank=True, choices=[('Schlagwort', 'Schlagwort'), ('Eigenname', 'Eigenname')], help_text='Art des Stichworts', max_length=250, verbose_name='Art des Stichworts'),
        ),
    ]
