# Generated by Django 3.1.5 on 2021-03-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0012_auto_20210329_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='related_keyword',
            field=models.ManyToManyField(blank=True, help_text='Steht in Verbindung zu anderem Stichwort', related_name='rvn_related_keyword', to='archiv.KeyWord', verbose_name='Stichwort'),
        ),
    ]
