# Generated by Django 3.2 on 2021-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0014_stelle_ort'),
    ]

    operations = [
        migrations.AddField(
            model_name='stelle',
            name='end_date',
            field=models.PositiveSmallIntegerField(blank=True, help_text="e.g. '1234'", null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='stelle',
            name='start_date',
            field=models.PositiveSmallIntegerField(blank=True, help_text="e.g. '300'", null=True, verbose_name='Start Date'),
        ),
    ]
