# Generated by Django 3.2 on 2021-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0017_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.IntegerField(blank=True, help_text='bis', null=True, verbose_name='bis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.IntegerField(blank=True, help_text='von', null=True, verbose_name='von'),
        ),
    ]
