# Generated by Django 3.2 on 2021-10-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0020_text_not_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='stelle',
            name='lemmata',
            field=models.TextField(blank=True, help_text='A lemmatized version of the quote', null=True, verbose_name='A lemmatized version of the quote'),
        ),
    ]
