# Generated by Django 3.2 on 2021-11-25 12:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0025_remove_text_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='story_map',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Story Map', null=True, verbose_name='Story Map'),
        ),
    ]
