# Generated by Django 3.2 on 2021-11-30 14:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0026_usecase_story_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='automatically populated', null=True, srid=4326, verbose_name='Coordinates'),
        ),
    ]
