# Generated by Django 3.2.9 on 2022-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0028_usecase_knightlab_stoy_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='end_date_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text="e.g. '350', Muss (!) als Zahl eingegeben werden", null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='autor',
            name='start_date_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text="e.g. '300'; Muss (!) als Zahl eingegeben werden", null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='art',
            field=models.CharField(blank=True, choices=[('Schlagwort', 'Schlagwort'), ('Eigenname', 'Eigenname'), ('Ethonym', 'Ethonym'), ('Region', 'Region'), ('Unsicher', 'Unsicher')], help_text='Art des Stichworts', max_length=250, verbose_name='Art des Stichworts'),
        ),
    ]
