# Generated by Django 3.2.9 on 2022-03-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0030_auto_20220203_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['id'], 'verbose_name': 'Autor'},
        ),
        migrations.AlterModelOptions(
            name='ort',
            options={'ordering': ['id'], 'verbose_name': 'Ort'},
        ),
        migrations.AlterModelOptions(
            name='stelle',
            options={'ordering': ['id'], 'verbose_name': 'Stelle'},
        ),
    ]
