# Generated by Django 3.2.9 on 2022-03-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0032_spatialcoverage_geom_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stelle',
            name='ort',
        ),
        migrations.AddField(
            model_name='stelle',
            name='ort',
            field=models.ManyToManyField(blank=True, help_text='Ort', related_name='rvn_stelle_ort_ort', to='archiv.Ort', verbose_name='Ort'),
        ),
    ]
