# Generated by Django 3.2.9 on 2022-03-23 12:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0033_auto_20220323_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='fuzzy_geom',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, help_text='fuzzy geom', null=True, srid=4326, verbose_name='fuzzy geom'),
        ),
    ]
