# Generated by Django 3.2.9 on 2022-03-28 11:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('archiv', '0034_ort_fuzzy_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='end_date',
            field=models.CharField(blank=True, help_text='Death or end of activity', max_length=250, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='gnd_id',
            field=models.CharField(blank=True, help_text='ID in GND', max_length=250, verbose_name='GND ID'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='jahrhundert',
            field=models.CharField(blank=True, help_text='Century or centuries active', max_length=250, verbose_name='Century'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Comment', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='legacy_pk',
            field=models.IntegerField(blank=True, help_text='Legacy id (from GENS database)', null=True, verbose_name='Legacy ID'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name',
            field=models.CharField(blank=True, help_text="Author's name in German", max_length=250, verbose_name='Name (de)'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name_en',
            field=models.CharField(blank=True, help_text="Author's name in English", max_length=250, verbose_name='Name (en)'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name_fr',
            field=models.CharField(blank=True, help_text="Author's name in French", max_length=250, verbose_name='Name (fr)'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name_gr',
            field=models.CharField(blank=True, help_text="Author's name in Greek", max_length=250, verbose_name='Name (gr)'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name_it',
            field=models.CharField(blank=True, help_text="Author's name in Italian", max_length=250, verbose_name='Name (it)'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name_lat',
            field=models.CharField(blank=True, help_text="Author's name in Latin", max_length=250, verbose_name='Name (lat)'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='orig_data_csv',
            field=models.TextField(blank=True, null=True, verbose_name='Original data'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='ort',
            field=models.ForeignKey(blank=True, help_text='Place associated with author (of birth or activity)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_autor_ort_ort', to='archiv.ort', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='start_date',
            field=models.CharField(blank=True, help_text='Birth or earliest year of activity', max_length=250, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.IntegerField(blank=True, help_text='End date or last possible date', null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.IntegerField(blank=True, help_text='Start date or earliest possible date', null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, help_text='Name of the event', max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='use_case',
            field=models.ManyToManyField(blank=True, help_text='Associated use case(s)', related_name='has_event', to='archiv.UseCase', verbose_name='Use case'),
        ),
        migrations.AlterField(
            model_name='event',
            name='written_date',
            field=models.CharField(blank=True, help_text='Specific year', max_length=250, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='art',
            field=models.CharField(blank=True, choices=[('Schlagwort', 'Schlagwort'), ('Eigenname', 'Eigenname'), ('Ethonym', 'Ethonym'), ('Region', 'Region'), ('Unsicher', 'Unsicher')], help_text='Type of keyword', max_length=250, verbose_name='Type of keyword'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Comment', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='legacy_pk',
            field=models.IntegerField(blank=True, help_text='Old primary key (from GENS database)', null=True, verbose_name='Old primary key'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name_gr',
            field=models.CharField(blank=True, help_text='Name in Greek', max_length=250, verbose_name='Name (gr)'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='orig_data_csv',
            field=models.TextField(blank=True, null=True, verbose_name='Original data'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='related_keyword',
            field=models.ManyToManyField(blank=True, help_text='Other keyword linked to this one', related_name='rvn_related_keyword', to='archiv.KeyWord', verbose_name='Linked keyword'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='stichwort',
            field=models.CharField(blank=True, help_text='Keyword', max_length=250, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='varianten',
            field=models.TextField(blank=True, help_text='Variants forms (separated with ;)', null=True, verbose_name='Variants'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='wurzel',
            field=models.CharField(blank=True, help_text='Root', max_length=250, verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='art',
            field=models.ForeignKey(blank=True, help_text='Type of place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_ort_art_skosconcept', to='vocabs.skosconcept', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordinates (automatically generated)', null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='fuzzy_geom',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, help_text='Approximate localisation of an area', null=True, srid=4326, verbose_name='Approximate localisation'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='kategorie',
            field=models.ForeignKey(blank=True, help_text='Category of place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_ort_kategorie_skosconcept', to='vocabs.skosconcept', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Comment', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='legacy_pk',
            field=models.IntegerField(blank=True, help_text='Old primary key (from GENS database)', null=True, verbose_name='Old primary key'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='long',
            field=models.FloatField(blank=True, help_text='Longitude', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the place in English', max_length=250, verbose_name='Name (en)'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='name_antik',
            field=models.CharField(blank=True, help_text='Name of the place in ancient sources', max_length=250, verbose_name='Name (ancient)'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name of the place in German', max_length=250, verbose_name='Name (de)'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='name_fr',
            field=models.CharField(blank=True, help_text='Name of the place in French', max_length=250, verbose_name='Name (fr)'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='name_gr',
            field=models.CharField(blank=True, help_text='Name of the place in Greek', max_length=250, verbose_name='Name (gr)'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='name_it',
            field=models.CharField(blank=True, help_text='Name of the place in Italian', max_length=250, verbose_name='Name (it)'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='norm_id',
            field=models.CharField(blank=True, help_text='Norm ID', max_length=250, verbose_name='Norm-ID'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='orig_data_csv',
            field=models.TextField(blank=True, null=True, verbose_name='Original data'),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='fuzzy_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Approximate localisation of an area', null=True, srid=4326, verbose_name='Approximate localisation'),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='fuzzyness',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='Uncertainty of location on a scale from 1 (very secure) to 10 (very insecure)', verbose_name='Degree of uncertainty'),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='key_word',
            field=models.ForeignKey(blank=True, help_text='Keyword associated with coverage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_spatial_coverage', to='archiv.keyword', verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Comment', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='stelle',
            field=models.ManyToManyField(blank=True, help_text='Passage associated with coverage', related_name='has_spatial_coverage', to='archiv.Stelle', verbose_name='Passage'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='display_label',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Display label'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='end_date',
            field=models.PositiveSmallIntegerField(blank=True, help_text="End date or last possible date'", null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='key_word',
            field=models.ManyToManyField(blank=True, help_text='Keyword(s) asssociated with the passage', related_name='rvn_stelle_key_word_keyword', to='archiv.KeyWord', verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Comment', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='legacy_pk',
            field=models.IntegerField(blank=True, help_text='Old primary key (from GENS database)', null=True, verbose_name='Old primary key'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='lemmata',
            field=models.JSONField(blank=True, help_text='A lemmatised version of the passage', null=True, verbose_name='Quotation (lemmatised)'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='orig_data_csv',
            field=models.TextField(blank=True, null=True, verbose_name='Original data'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='ort',
            field=models.ManyToManyField(blank=True, help_text='Place of composition', related_name='rvn_stelle_ort_ort', to='archiv.Ort', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='start_date',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Start date or earliest possible date', null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary', null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='translation',
            field=models.TextField(blank=True, help_text='Translation', null=True, verbose_name='Translation'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='use_case',
            field=models.ManyToManyField(blank=True, help_text='Associated use case(s)', related_name='has_stelle', to='archiv.UseCase', verbose_name='Use case'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='zitat',
            field=models.TextField(blank=True, help_text='Text of the passage in the original language', null=True, verbose_name='Quotation'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='zitat_stelle',
            field=models.CharField(blank=True, help_text='Chapter and/or page numbers for the passage', max_length=250, null=True, verbose_name='Quotation source'),
        ),
        migrations.AlterField(
            model_name='text',
            name='alt_title',
            field=models.CharField(blank=True, help_text='Alternative title(s) of the text', max_length=250, verbose_name='Alternative title'),
        ),
        migrations.AlterField(
            model_name='text',
            name='art',
            field=models.ForeignKey(blank=True, help_text='Genre of text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_text_art_skosconcept', to='vocabs.skosconcept', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='text',
            name='autor',
            field=models.ManyToManyField(blank=True, help_text='Author', related_name='rvn_text_autor_autor', to='archiv.Autor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='text',
            name='end_date',
            field=models.CharField(blank=True, help_text='Last possible date of composition', max_length=250, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='text',
            name='jahrhundert',
            field=models.CharField(blank=True, help_text='Century', max_length=250, verbose_name='Century'),
        ),
        migrations.AlterField(
            model_name='text',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Comment', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='text',
            name='legacy_pk',
            field=models.IntegerField(blank=True, help_text='Old primary key (from GENS database)', null=True, verbose_name='Old primary key'),
        ),
        migrations.AlterField(
            model_name='text',
            name='orig_data_csv',
            field=models.TextField(blank=True, null=True, verbose_name='Original data'),
        ),
        migrations.AlterField(
            model_name='text',
            name='ort',
            field=models.ManyToManyField(blank=True, help_text='Place of composition', related_name='rvn_text_ort_ort', to='archiv.Ort', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='text',
            name='start_date',
            field=models.CharField(blank=True, help_text='Earliest possible date of composition', max_length=250, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_lang',
            field=models.CharField(blank=True, default='lat', help_text='Language of the original text (default Latin)', max_length=250, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the text', max_length=250, verbose_name='Title'),
        ),
    ]
