# Generated by Django 3.2.9 on 2022-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0037_usecase_custom_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='art',
            field=models.CharField(blank=True, choices=[('Keyword', 'Keyword'), ('Name', 'Name'), ('Ethonym', 'Ethonym'), ('Region', 'Region'), ('unclear', 'unclear')], help_text='Type of keyword', max_length=250, verbose_name='Type of keyword'),
        ),
    ]
