# Generated by Django 4.0.7 on 2022-11-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0042_usecase_show_layer_alter_autor_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecase',
            old_name='show_layer',
            new_name='show_labels',
        ),
    ]
