# Generated by Django 4.0.7 on 2022-11-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0043_rename_show_layer_usecase_show_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spatialcoverage',
            name='show_labels',
        ),
    ]
