# Generated by Django 4.0.8 on 2023-01-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0044_remove_spatialcoverage_show_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='custom_layer',
        ),
        migrations.AlterField(
            model_name='stelle',
            name='ort',
            field=models.ManyToManyField(blank=True, help_text='Places mentioned in the passage', related_name='rvn_stelle_ort_ort', to='archiv.ort', verbose_name='Place'),
        ),
    ]
