# Generated by Django 4.0.7 on 2023-01-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0045_remove_usecase_custom_layer_alter_stelle_ort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stelle',
            name='ort',
        ),
    ]
