# Generated by Django 4.0.7 on 2023-01-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0046_remove_stelle_ort'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='published',
            field=models.BooleanField(default=False, help_text='True if the use case should be presented in the frontend, false if not', verbose_name='Published'),
        ),
    ]
