# generated by appcreator
import django_filters

from .models import AboutTheProject, ProjectInst, TeamMember


class TeamMemberListFilter(django_filters.FilterSet):
    class Meta:
        model = TeamMember
        fields = "__all__"


class AboutTheProjectListFilter(django_filters.FilterSet):
    class Meta:
        model = AboutTheProject
        fields = "__all__"


class ProjectInstListFilter(django_filters.FilterSet):
    class Meta:
        model = ProjectInst
        fields = "__all__"
